insert into brand (id, name) values (1, 'Dell');
insert into brand (id, name) values (2, 'Alienware');
insert into brand (id, name) values (3, 'MSI');
insert into brand (id, name) values (4, 'Razer');
insert into brand (id, name) values (5, 'ASUS');
insert into brand (id, name) values (6, 'HP');
insert into brand (id, name) values (7, 'Acer');
insert into brand (id, name) values (8, 'Apple');
insert into brand (id, name) values (9, 'Lenovo');

insert into category (id, name) values (1, 'Scanner');
insert into category (id, name) values (2, 'Ultrabook');
insert into category (id, name) values (3, 'Scanner');
insert into category (id, name) values (4, 'Laptop');
insert into category (id, name) values (5, 'Smartphone');
insert into category (id, name) values (6, 'Desktop PC');
insert into category (id, name) values (7, 'Laptop');
insert into category (id, name) values (8, '2-in-1 Laptop');
insert into category (id, name) values (9, 'Gaming Console');
insert into category (id, name) values (10, 'Printer');
insert into category (id, name) values (11, 'Virtual Reality Headset');
insert into category (id, name) values (12, 'Ultrabook');
insert into category (id, name) values (13, 'Bluetooth Speaker');
insert into category (id, name) values (14, '2-in-1 Laptop');
insert into category (id, name) values (15, 'Chromebook');
insert into category (id, name) values (16, 'USB Flash Drive');
insert into category (id, name) values (17, 'Wireless Earbuds');
insert into category (id, name) values (18, 'Printer');
insert into category (id, name) values (19, 'Gaming Console');
insert into category (id, name) values (20, 'All-in-One PC');

insert into discount (id, name, percentage) values (1, 'Fall Harvest Deals', 50);
insert into discount (id, name, percentage) values (2, 'End of Year Clearance', 25);
insert into discount (id, name, percentage) values (3, 'Back to School Sale', 15);
insert into discount (id, name, percentage) values (4, 'Holiday Blowout', 10);
insert into discount (id, name, percentage) values (5, 'End of Year Clearance', 20);